### ISSUE TITLE
Stuck on login screen.

### ISSUE THREAD

**Issue by Rietty** [cursey/kanan-new#101]
G23 update and the subsequent patches seem to have left it half usable atm, kanan loads but gets stuck on the login screen atm. https://media.discordapp.net/attachments/443619966470848533/591462140179775488/unknown.png

Just made an issue in case weren't aware of this/if anyone else wanted to check it out.

**Comment by cursey** [comment]
I don't get stuck on login screen. I'll look into it though.

**Comment by kyouano** [comment]
I'm having the same problem with the latest changes.

**Comment by Arceni** [comment]
[log.txt](https://github.com/cursey/kanan-new/files/3313510/log.txt)
Client stuck. Here kanan log with everything happened before i rageclosed client.

**Comment by Warsen** [comment]
I'd be surprised if there was anyone who didn't have an issue with mods after this patch/maintenance. I believe Nexon updated BlackCipher. I've been using the old version of kanan (for Python). Before I had even patched the game this morning I was still on version 299, I tried running it as usual only to have an error message from BlackCipher which asked me to make a support ticket about this issue.

I always forget to patch. So afterwards I logged in through Nexon Launcher to patch and start the game once. Game works as intended without mods. Now when I try to use old Kanan (for Python) everything fails to patch. Couple of access violation errors are given before failure notices. It sounds like they protected the executable.

I'm going to switch to Kanan-new. Will probably have similar issues though, I blame the external security system.

**Comment by cursey** [comment]
> I'd be surprised if there was anyone who didn't have an issue with mods after this patch/maintenance. I believe Nexon updated BlackCipher. I've been using the old version of kanan (for Python). Before I had even patched the game this morning I was still on version 299, I tried running it as usual only to have an error message from BlackCipher which asked me to make a support ticket about this issue.
> 
> I always forget to patch. So afterwards I logged in through Nexon Launcher to patch and start the game once. Game works as intended without mods. Now when I try to use old Kanan (for Python) everything fails to patch. Couple of access violation errors are given before failure notices. It sounds like they protected the executable.
> 
> I'm going to switch to Kanan-new. Will probably have similar issues though, I blame the external security system.

They just updated their compiler which is why everything fails to patch. None of their security stuff has changed (except that they no longer compress `client.exe`). The reason kanan-new is hanging during initialization is because patches are failing which means pattern scanning is much slower. I'll fix it soon.

**Comment by cursey** [comment]
Probably fixed (4eefee1). Let me know if its not.

**Comment by Warsen** [comment]
> Probably fixed ([04a2668](https://github.com/cursey/kanan-new/commit/04a26684694636568127e3897cb190ebe1cad9df)). Let me know if its not.

I can confirm I get past the login screen and into character selection. My game closes after I log in to a character. At least some amount of patches are causing the game to auto-close. I'll open a separate ticket if I can isolate any problems I'm experiencing.
