### ISSUE TITLE
[SUGGESTION] Parameterize Borderless Window Size & Location

### ISSUE THREAD

**Issue by Warsen** [cursey/kanan-new#104]
I'm the owner of a large 43 inch computer monitor with a 4K resolution, It would be really great if users could specify the X and Y position and the width and height of the window in the options for borderless window. One might use this to display the game in a 1920x1080 quadrant in any corner of the screen.

I didn't want to bother you with doing this, I wanted to contribute myself, but actually I am unable to compile Kanan-new. After cloning the repository and attempting to build it, none of the files in the Launcher project are capable of referencing files from the Core project. For example, App.cpp won't compile because it can't find String.hpp. I can not remember how to fix this.

**Comment by cursey** [comment]
This would be easy to add. I do not know why you're having trouble building kanan-new. No changes to the projects or solution should be necessary (appveyor automatically builds the entire project each time a commit is pushed without any issues).

I can look into adding this after I finish fixing patches.

**Comment by Warsen** [comment]
I figured out why it wouldn't compile. Your project file Launcher\Launcher.vcxproj has defined additional include directories which includes '$(SolutionDir)/Core', but only for the 'Release|Win32' and 'Debug|Win32' configurations. These includes are missing for 'Release|x64' and 'Debug|x64' configurations. My VS IDE defaulted to using 'Debug|x64', so it wouldn't compile. To avoid new users unable to compile, you could either to copy options from the Win32 configurations into x64 configurations or remove the x64 configurations.

Anyways I'll wait and see if you implement position, width, and height options. Thanks.

**Comment by cursey** [comment]
I did it real quick just now cause (855ef9935c991e899ac213c21707feab80acf74a). Let me know if that fulfills your request.

**Comment by Warsen** [comment]
It works great. Thank you. Closing issue.
