### ISSUE TITLE
[SUGGESTION] Bring back unlimited crafting queue

### ISSUE THREAD

**Issue by Asurakun1** [cursey/kanan-new#112]
This was a fantastic mod that allowed us to afk while the crafting does its work. It's nice to craft in bulk instead of having to repeat the process of crafting 20 items when we desired more.

**Comment by HammerSnuggle** [comment]
It's a memory patch.  I haven't tested it for latest versions, but you can try adding it to your patches.json.
Last time I confirmed it to be working was about 2 months ago, so it's recent enough.

```    {
        "name": "Uncap Production",
        "desc": "Read.  It uncaps production.",
        "category": "Fixes",
        "patches": [
            {
                "pattern": "66 39 86 ? ? ? ? 76 07 66",
                "offset": 7,
                "patch": "EB",
                "n": 0
            },
            {
                "pattern": "66 39 86 ? ? ? ? 76 07 66",
                "offset": 7,
                "patch": "EB",
                "n": 1
            }
        ]
    },

**Comment by Asurakun1** [comment]
where can i find this patches.json?

**Comment by HammerSnuggle** [comment]
patches.json comes with Kanan, so it would end up being in the mabinogi folder.  Also I tested it yesterday, it still works.  Just open Patches.json with notepad, and add that code after the first line (which should be a single square bracket [   ).  Good luck.

**Comment by Asurakun1** [comment]
ooh okay. Thankyou very much
