### ISSUE TITLE
Kanan Launcher issue [key 'access_token' not found]

### ISSUE THREAD

**Issue by Asurakun1** [cursey/kanan-new#116]
[json.exception.out_of_range.403] 
This error is given upon trying to open a new mabi client for multi client or single client purposes.
account credentials are correct.

**Comment by cursey** [comment]
Yeah the launcher was just a quick project I threw together so the error messages are really bad. Usually that means either you didn't enter your email/password correctly or you need to login via the nexon launcher 1 time on that account before using kanan launcher.
