### ISSUE TITLE
Kanan PatcherSetting.json

### ISSUE THREAD

**Issue by Galeronis** [cursey/kanan-new#118]
I saw a post that you said for the current run to have no issues that the same folder with Loader.exe cannot have multiple .json files in it.  I saved my settings to the Kanan ingame overlay and it created a PatchSettings.json file, causing an issue.  I then moved the Kanan.dll, Loader.exe, and Patcher.json files into a separate folder and it has completely taken away the overlay and any access to Kanan in itself.  Any suggestions on how to correct this?

**Comment by cursey** [comment]
I have no idea what `PatchSettings.json` is. Kanna doesn't generate a file called `PatchSettings.json`. Just put the files from `kanan.zip` in its own folder.

**Comment by Galeronis** [comment]
Alright.  It only popped up after I went to the Kanan menu and clicked "Save File", is there anything to do with that by chance?

**Comment by cursey** [comment]
Kanan saves settings in a file called `config.txt`.

**Comment by Galeronis** [comment]
Hmm, I wonder where it came from then.  I deleted one earlier to make it work properly, and when I saved the file it did that.  But I will do as you suggest and move from there.  Thank you for your time!

Also, it was "PatcherSettings.json" to be completely correct on the file it produced.

**Comment by Galeronis** [comment]
{
  "IgnorePackagehFolder": true,
  "ForceUpdateCheck": false
} 

These are the contents of it as well, incase anyone else happens to have the issue.  Sorry for the multiple replies.

**Comment by Aahzmandius** [comment]
Just so there's no confusion, PatcherSettings.json is a file from Hyddwn, you should really put things in their own folders lol...

**Comment by Galeronis** [comment]
I appreciate the info.  My only problem was I had one of those that was generated on a clean Mabi before I put the new Hyddwen Launcher in it.  And then the second was generated after, so i didn't think anything of it.  And they usually are in separate folders, so i appreciate the unneeded sarcasm with it.  Thanks for the issue being resolved :)

**Comment by Galeronis** [comment]
I much appreciate the answer to where it came from.  Originally I had one displayed from what I thought was prior to me putting Hyddwn in, and the last Hyddwn I had was in a secondary folder, but I did a clean install on Mabi when everything was acting up, so I will remake one for Hyddwn.  Thank you for the answer on where it came from!

**Comment by Seeker1437** [comment]
Thanks for this.

The issue is confirmed.

Hyddwn/HyddwnLauncher#31
