### ISSUE TITLE
Please update the old kanan launcher code if you can

### ISSUE THREAD

**Issue by Millenniumfei** [cursey/kanan-new#122]
Hello, I knew that you been updates the launcher file on new kanan, but is there any chance you can write the code into python? Thank you.

**Comment by Aahzmandius** [comment]
Not sure there's a point to updating the old python version, what about it do you need?

**Comment by xCryptic** [comment]
#123 is a good reason to do it :>

**Comment by y3tii** [comment]
Can't you use another launcher? And just use kanan's loader.

**Comment by shaggyze** [comment]
> #123 is a good reason to do it :>

nope, that's not a good reason to do it, as once that error is fixed for you in kan-new there will be no need for having the old python launcher.

**Comment by cursey** [comment]
I think I fixed that error.

**Comment by Millenniumfei** [comment]
> I think I fixed that error.

Yes, you did fix it, thank you! :D

**Comment by cursey** [comment]
You're welcome.
