### ISSUE TITLE
Failed to query the registry

### ISSUE THREAD

**Issue by xCryptic** [cursey/kanan-new#123]
when using the launcher, I try to launch and get this error

![error](https://i.imgur.com/rQD022d.png)

I have it set to client.exe and have no added launch settings. this has been an error for awhile actually but I've been using the old launcher

**Comment by Seeker1437** [comment]
32bit Windows?

**Comment by xCryptic** [comment]
no I'm on 64bit

**Comment by Galeronis** [comment]
Just had my friend download VS2019 and Kanan and set it up and he's getting this error as well.  He doesn't multiclient so it's not necessary for him, but I figured I'd help him set it up just incase.  Unfortunately this was the error I haven't been able to figure out.

**Comment by cursey** [comment]
As far as I can tell this only happens on Windows 7. I don't know if it happens to everyone using Windows 7 or just some people. At any rate, I don't use Windows 7 so I can't easily fix it.

**Comment by Galeronis** [comment]
My friend says he is running on Windows 8.1.  Not sure if that's going to make any difference.

**Comment by cursey** [comment]
I think I've fixed the issue (19e65c28bf12db80fba4730d1b63d91cec73d7d5). Please try it and let me know.

**Comment by xCryptic** [comment]
now I'm getting failed to send request

![ ](https://i.imgur.com/cIHofuL.png)

**Comment by cursey** [comment]
Confirmed fixed in #122. @xCryptic that error is unrelated and I don't know why you're getting it.
