### ISSUE TITLE
"[json.exception.out_of_range.403] key 'id_token' not found"

### ISSUE THREAD

**Issue by Retuna** [cursey/kanan-new#125]
"[json.exception.out_of_range.403] key 'id_token' not found" Error dialog pops up when trying to launch a Client, Account Credentials are correct, and can be launched normally from Nexon Launcher without issue, there were no issues on previous days.

**Comment by Retuna** [comment]
Solved by logging off from Nexon Launcher, and logging back in, Nexon Launcher Asked for a Confirmation Code sent by E-Mail

**Comment by LoneDev6** [comment]
Would be nice to be notified with a proper error message from kanan launcher
