### ISSUE TITLE
Equip Override Colors Broken

### ISSUE THREAD

**Issue by Peechiee** [cursey/kanan-new#144]
This has been a problem for a while now. Saving Config.txt with the correct colors saves the right values, however when you close/reload the game, all of the values on the Kanan interface load incorrectly. Re-opening Config.txt shows that when Kanan is referencing it during the game opening, the values are still correct in the text on load, but they are not translating properly. I didn't recognize the color values, so to test this I put in the intended colors using the interface in game, saved a copy of the Config.txt generated with the right values, restarted my game, and then generated a new Config.txt using the new Hex codes that came up as the wrong colors on the interface. The ones that are showing up wrong the interface when the game starts were completely incorrect upon saving it after restarting the game. For example, the value I selected was (16769468) but when I load the game the interface loads the value (16777148).

I tried changing compatibility modes for Kanan, trying different inputs (like switching the 8-digit codes for Hex, RGBA, etc) to see if they would be accepted. The log says it's reading the Config.txt file and everything else works properly so I honestly have no idea where this issue stems from. I don't have a lot of knowledge on programming but I hope my bit of troubleshooting helps us get a little closer to a solution.

![image](https://user-images.githubusercontent.com/8453692/77212205-a1e96b80-6adc-11ea-8e52-db0dc2be613d.png)

![image](https://user-images.githubusercontent.com/8453692/77212237-bf1e3a00-6adc-11ea-94bb-400ff5d2d7fe.png)

**Comment by ericchase** [comment]
From a quick glance at the code, it appears that color values are being converted from ints to floats. Now, I have absolutely no clue if this would make that kind of difference, but it's the first thing I would personally look into.

Furthermore, the test is actually quite simple:
![2020-03-21--00 49 07](https://user-images.githubusercontent.com/30473157/77220410-cf024200-6b0d-11ea-8581-216889408e71.png)

**Comment by cursey** [comment]
Well I can tell you why we use floats for colors in kanan when the game and config expect ints. It's because the `ImGui::ColorEdit4` widget uses floats. If we want to use this widget without modification some conversion between ints to floats must occur.

I can also tell you why it's broken. It's because `convertIntColorToFloat` is just plain wrong. I'm pretty sure I wrote the function so I'll take responsibility and fix it.

**Comment by cursey** [comment]
It is done 686bf0daf2fc04eec2e9c87d853c763cca04d176. Please test it and let me know if this fixes the issue.

**Comment by Peechiee** [comment]
It's working properly now. The only small issue I ran into was a false positive on my antivirus, but nothing an exception couldn't fix, of course. Thank you both for your help! As always, super appreciated! :)
