### ISSUE TITLE
Equipment override not working on June 18 patch

### ISSUE THREAD

**Issue by jzpx** [cursey/kanan-new#147]
Hi, it seems that the equipment override component isn't working anymore after the June 18 patch. Happens on both color and item overrides.

The others that I use are still working tho (i.e. CP reader, freeze time of day), I'm not sure about the others.

**Comment by cursey** [comment]
I will fix it soon.

**Comment by cursey** [comment]
Fixed in commit 9dc5a77c52a99d71cb9c98628140d8dc00cc02c3. Let me know if it's fixed for you.

**Comment by jzpx** [comment]
Working great now, thanks a lot!
