### ISSUE TITLE
Best way to access the d3d9 hook from outside the main kanan script?

### ISSUE THREAD

**Issue by AverageSpearman** [cursey/kanan-new#148]
I'm wondering about how to go about using the "reusable d3d9 hook" in ways other than what ImGui already does. How do I cleanly access the d3d9 hook that appears to be declared in the main kanan.cpp script from within a new script? I can see that imgui simply gets its own pointer to it when it's initialized, but what would be a clean way to access the hook, given that there's no public methods in the kanan script available to get to it? Should I be reaching for the hook (and the d3d9 device with it) at all, or is there a way I can go through ImGui to do things like draw lines and shapes on the screen?

**Comment by cursey** [comment]
Reusable in this context means nothing about the D3D9 hook is specific to Mabi. If you want to use the D3D9 hook for some other game just use the /Core/ library along with D3D9Hook.hpp/cpp. It should be pretty straightforward. You might need to remove the logging.

**Comment by AverageSpearman** [comment]
Oh, that makes more sense now. Thanks for clarifying!
