### ISSUE TITLE
CCameraState "viewMatrix" field actually contains camera's Transform Matrix

### ISSUE THREAD

**Issue by AverageSpearman** [cursey/kanan-new#149]
It's kind of inconsequential, but I've been throwing my head against trying to do a world point to screen point conversion using the available memory reads and only now figured out that I still needed to invert the available matrix. Perhaps the field could be changed just for clarity.

**Comment by cursey** [comment]
I had a world to screen function in a private build but haven't touched it in years. I'll accept a PR for improvements to the camera structs if you get it working. I believe in my version I just calculated a matrix myself from the games camera pos, fov & screen size. Using the games matrix would be better.
