### ISSUE TITLE
Unable to get character target after p.e.t update

### ISSUE THREAD

**Issue by AverageSpearman** [cursey/kanan-new#152]
Must be something to do with the update change the character structure (maybe related to a flag for fynni gems?)

**Comment by cursey** [comment]
This should also be fixed by commit ee9abf286f38c2335c844e3217721c0d8746b6fe. Let me know.

**Comment by AverageSpearman** [comment]
Yep, looks like the location for the target id did get displaced. Thanks for the fix!
