### ISSUE TITLE
Equipment override not working after July 16 patch

### ISSUE THREAD

**Issue by jzpx** [cursey/kanan-new#153]
Hi, this happens on both color and item overrides..
The others that I use are still working tho (i.e. CP reader, freeze time of day), I'm not sure about the others..

**Comment by cursey** [comment]
Fixed in commit ee9abf286f38c2335c844e3217721c0d8746b6fe. Let me know if it works for you.

**Comment by jzpx** [comment]
It's perfectly working again, thanks a lot!
