### ISSUE TITLE
Auto set MTU not working

### ISSUE THREAD

**Issue by HarleySalas** [cursey/kanan-new#154]
Seems to be working quite strange.

(Yes, I've set it to the correct adapter and saved the config)

Upon updating the config nothing is changed, as is expected. After changing channels and viewing the logs, I get the following in rapid succession:
`
Lowered MTU successfully.
Restored MTU successfully
`

So it seems to just automatically restore it, rather than keep the lowered MTU.

Upon running _netsh interface ipv4 show subinterface_ it still shows that I have 1500 MTU, so the logs appear to be accurate.

Is there anything I might be missing?

**Comment by cursey** [comment]
MTU is set per connection. It restores it immediately after lowering it because it only needs to be lowered when the connection is made. No reason to impact other networked applications unnecessarily.

**Comment by HarleySalas** [comment]
should close issues, rip.

I noticed that windows 10 has an mtu minimum of 576; are you aware of any way to bypass this minimum? Almost feels like no one else in the world, except for mabi players seems to have the desire to make it something like 48, lol.
