### ISSUE TITLE
Equipment Override no longer working after 9/10 patch

### ISSUE THREAD

**Issue by dvrus** [cursey/kanan-new#160]

**Comment by cursey** [comment]
Should be fixed w/ commit 7b38636af0a50cf367b87f210637df0c63af61da. Let me know if it works for you.

**Comment by dvrus** [comment]
> Should be fixed w/ commit [7b38636](https://github.com/cursey/kanan-new/commit/7b38636af0a50cf367b87f210637df0c63af61da). Let me know if it works for you.

Fixed! Thank you so much.
