### ISSUE TITLE
Custom borderless fullscreen no longer working after Quality of Life update

### ISSUE THREAD

**Issue by AverageSpearman** [cursey/kanan-new#162]
I know they put in a borderless fullscreen in by default but I did like being able to have a custom size that lets me keep my taskbar on screen.
Also, what programs do you use to read the memory addresses used by the game? I tried HeapMemView but found that it couldn't read some memory addresses (such as those that would contain characters)

**Comment by cursey** [comment]
Seems to work for me. I use a combination of tools such as ReClass.NET, Cheat Engine, and x64dbg depending on what I'm trying to do.

**Comment by AverageSpearman** [comment]
Alright it just seems to be a little finicky but works.
