### ISSUE TITLE
Kanan launcher unsafe uses old launcher APIs any plans to update?

### ISSUE THREAD

**Issue by modernsupport** [cursey/kanan-new#164]
Bans happen every thursday

**Comment by Seeker1437** [comment]
Yes, I am working on a pull request currently to fix this.

**Comment by cursey** [comment]
I haven't been banned.

**Comment by cursey** [comment]
I don't think anyone actually got banned for using the old API but I did update it anyway. See commit fa7a8f34526bae390337182b364eb8c0e41559ef. Willing to accept a better PR that doesn't use a bogus `captcha_token` but this works just as good as the old launcher API did for now.
