### ISSUE TITLE
Equipment Override - Color doesn't work

### ISSUE THREAD

**Issue by pommyz** [cursey/kanan-new#167]
Hi I was able to override color for all parts before the latest mabi update
Now I can't

**Comment by sportpp** [comment]
Can confirm. It seems the entire 'Equipment Override' section isn't functioning at the moment.

**Comment by cursey** [comment]
Fixed with commit be7ebf584062cd4f8fd23dfd312453793ea0d9b4. Please download the latest build and let me know if its fixed for you.

**Comment by sportpp** [comment]
'Equipment Override' and all its functions are working properly now. Thanks Cursey!
