### ISSUE TITLE
Equipment override isn't working

### ISSUE THREAD

**Issue by Sebteddy** [cursey/kanan-new#171]
I've been trying to use the equipment override lately i though it was my not reloading the game but i think it's something with kanan?

**Comment by sportpp** [comment]
Confirmed Equip Override doesn't work

**Comment by cursey** [comment]
I'll fix it soon.

**Comment by cursey** [comment]
Should be fixed by commit a3aa8af77d6d1e6ba86e22710fc30e1603db1e3d. Download the latest and let me know if it works for you.

**Comment by sportpp** [comment]
Working as intended. Thanks Cursey!
