### ISSUE TITLE
I can't open the game 

### ISSUE THREAD

**Issue by ofov85** [cursey/kanan-new#176]
After the last update, it has not let me open with the launcher, it gives me an error.

[json.exception.out_of_range-403] key 'id_token' not found.

Failed to start Cliet.exe! Please check your settings and make sure you can login to the account from this computer normally.

I can access the account normally.

**Comment by Seeker1437** [comment]
I am currently implementing a fix in Hyddwn Launcher I will then port to Kanan Launcher unless someone else does it before me.

**Comment by ofov85** [comment]
Thank you very much for the prompt response, I look forward to the new patch.

**Comment by cursey** [comment]
So I just did a quick look at the changes and it seems like its a simple fix. I'll work on fixing kanan launcher now.

**Comment by cursey** [comment]
Alright I've pushed a commit that should fix login issues with the Launcher project: b5d1328014eade5b83e92ddcdfecfe602c7f4990. Let me know if it works for you.

**Comment by Warsen** [comment]
In my experience, accounts that I had previously not needed to [verify my device] on now need to be verified. Accounts that I had not done that for over 2 years needed me to verify again. For anyone who doesn't know how to do it, log yourself in through the Nexon Launcher and checkmark it to remember your device when prompted for your verification code.

**Comment by ofov85** [comment]
Thank you very much for the comment friend Warsen, but as Sekeer1437 and Cursey already comment, it is a change due to the update.

After the update, I was logging in normally with the account, but the Kanna launcher could not start the client.

Again, thanks to Cursey and Sekeer1437 for such a quick response and even more so for repairing the launcher so quickly.

**Comment by Warsen** [comment]
I know it, I was commenting to affirm that the updated code works for me and then add some steps that may help users who play with many accounts. Glad to hear it works for you; It seems the issue is fully resolved.
