### ISSUE TITLE
Cannot for the life of me figure out the launcher

### ISSUE THREAD

**Issue by Altailion** [cursey/kanan-new#178]
All my files are up to date. (i've checked about 3 times and made sure they were all current) I've put in all the correct information for the login and everytime it pops up with, _"Failed to query header size"_ and then goes, _"Failed to start client.exe! Please check your settings to make sure you can login to the account from this computer normally."_ Which i checked and made sure i did the security check on the normal nexon page login security mumbo jumbo to remember the computer and it just doesn't want to work for me. I also make sure I don't have any mabi clients open when trying to get this to work.  Am I doing anything wrong? If so please correct me I'd love to figure this out so I can launch through kanan's launcher. ^^
Side note that might be useful information? To normally play I launch through steam, the normal nexon mabinogi launcher just never agreed with my computer but i've always had steam work, as well as Hydwnn, but I am aware Hydwnn is in currently under construction at the moment which is why I want to see if I can get Kanan's launcher to work.

**Comment by sentimeta0** [comment]
Hey, did you ever manage to fix this? Having exactly the same problem, getting "failed to query header size" and then failing to start client.exe.

**Comment by Altailion** [comment]
Oh yeah the issue is you need to launch through the normal Mabinogi launcher, not through steam. Once you do that then it'll let you verify your account through that launcher. Once you've done that you'll be able to launch through the Kanan launcher just fine. It took me a while and some help but yeah you just gotta download the normal mabinogi launcher, launch through that on your mabi account and it should ask to verify. Once verified it should work!

**Comment by robertmaxton42** [comment]
As of yesterday's maintenance, this workaround doesn't seem to work anymore.

**Comment by shaggyze** [comment]
> As of yesterday's maintenance, this workaround doesn't seem to work anymore.

the above user failed to mention that sometimes you need to login to nexon's website, go to account security and remove trusted devices, then log out of the launcher, log back in and check remember this device, then it should fix "failed to query header size"

**Comment by A-G-97** [comment]
Chiming in over a year later to say that this issue still exists, and the suggested workarounds did not fix it.
