### ISSUE TITLE
Suddenly unable to log in using Kanan

### ISSUE THREAD

**Issue by the-big-G** [cursey/kanan-new#184]
Was able to use Kanan launcher up until May 30th. Tried logging in today with my main account and got the error:
[https://www.nexon.com/api/account/v1/no-auth/login/launcher]

Failed to query header size: The requested header was not found.

Pressing the OK button follows it up with a window saying:
Failed to start Client.exe! Please check your settings and make sure you can login to the account from this computer normally.

My alt accounts are still able to log in without issue.
Things I've tried: 
-changing the username to a different email
-changing the password
-syncing to internet time
-reinstalling the game
-removing and re-adding my computer to trusted devices.

I am still able to log in via the Nexon launcher without issue however.

**Comment by cursey** [comment]
See #182
