### ISSUE TITLE
Auto enter Secondary Password issues

### ISSUE THREAD

**Issue by PoiDoe** [cursey/kanan-new#193]
![vmware_EpQDL80H8p](https://user-images.githubusercontent.com/20039012/132823036-d547ebdd-3af9-494a-95f7-88c2f16cea4e.png)

upon only turning on "enable secondary password" and restarting the client, the mod does not enter a secondary password.
spams the message above, however.
auto login still works.
above message is also spammed during normal gameplay

**Comment by cursey** [comment]
I fixed this a few hours ago in commit ae2684afc704524cb87f59f46f16ee9bccda4bd6. Did you not grab that change?

**Comment by PoiDoe** [comment]
oh lol my build was behind. all goods
