### ISSUE TITLE
Boarderless window bug

### ISSUE THREAD

**Issue by PoiDoe** [cursey/kanan-new#2]
when enabling boarder-less window the game only appears as a small box in the top right of the screen. 
https://i.imgur.com/isEQckM.jpg
running two monitors if that means anything
also using steam verson of mabi

**Comment by cursey** [comment]
Yeah I've also had that happen to me once or twice. I can't trigger it reliably though, can you? If you can, what are the steps you take to trigger this problem? I'll go over the code for that feature again and see if anything stands out.

**Comment by PoiDoe** [comment]
for me it happens every time i try and use it. 
Video cause bad at listing steps
https://www.youtube.com/watch?v=w2wVchpkFhk&

**Comment by PoiDoe** [comment]
A quick fix i found was to change 
BorderlessWindow.Choice=0
to 
BorderlessWindow.Choice=1

when the game launches with this changing the settings seems to not break the window

**Comment by Seeker1437** [comment]
I think this is related to a bug in how mabi manages desktop screens. Proff found a way around it, but you'd need to ask because I don't quite understand it.

**Comment by cursey** [comment]
I've played with the logic a little and it seems more reliable for me after the changes in commit dd956b3. If you could try it that would be great.

**Comment by PoiDoe** [comment]
Seems to have fixed it on my side. thank you
