### ISSUE TITLE
opening change channel crashes game

### ISSUE THREAD

**Issue by jabin1233** [cursey/kanan-new#203]
when opening the channel switch menu while "disable channel move description" is enabled causes a crash

**Comment by nugusaeyo** [comment]
Can confirm as well

**Comment by PoiDoe** [comment]
opening a dmp of client created at crash gives me this

Unhandled exception at 0xBF4BF69C in Client.dmp: 0xC0000005: Access violation reading location 0xBF4BF69C.

no idea how to fix it personally but might help cursey / who ever patches it

**Comment by shaggyze** [comment]
> opening a dmp of client created at crash gives me this
> 
> Unhandled exception at 0xBF4BF69C in Client.dmp: 0xC0000005: Access violation reading location 0xBF4BF69C.
> 
> no idea how to fix it personally but might help cursey / who ever patches it

pretty sure it's only going to be a minor change as blade already fixed ChMoveDescCut so it will be a quick fix she can do on her own as soon as she's able.

**Comment by cursey** [comment]
Fixed in commit b3c51817502195a5ecfa24a05e48bc28ace034db. Please try downloading the latest artifact to confirm that its working and let me know https://ci.appveyor.com/project/cursey/kanan-new/build/artifacts

**Comment by jabin1233** [comment]
confirmed it is fixed
