### ISSUE TITLE
Trying to download Kanan on a new comp and Loader fails to inject

### ISSUE THREAD

**Issue by Altailion** [cursey/kanan-new#207]
Hi so I just got a new computer and ofc need to re download Kanan. Well i got everything working fine except the Loader.exe 
When i try to inject I get 
"Waiting for Mabinogi window(s) . . .
Opening process . . .
Couldn't find "C:\\Users\\Writt\\Downloads\\kanan\\kanan.dll" to inject. Skipping . . .
"
Am I missing something perhaps?

**Comment by cursey** [comment]
Did your antivirus delete `kanan.dll`?

**Comment by Altailion** [comment]
Oh it did, I didn't notice it was missing but I got it now! Thank you this fixed it!! <3
