### ISSUE TITLE
Request: Display Worn Item IDs In Character List

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan-new#22]
Sometimes a player has "View Equipment" turned off so you can't see their gear in detail, but you still at least want to know what something they're wearing is in general (even if you can't see the stats/enchants), like "What dress is that?!"

The entity list currently gets and displays some info on each loaded character through what appears to be the following chain (according to the ReClass file in the source).
>CCharacterList+0x4
>-CCharacterListNode+0x0
>--CCharacterListNodeEntry+0x10
>---CCharacter+0x90
>----CParameter+whatever

The item IDs that are being used on that character are available in that chain via...
>---CCharacter+0x224
>----CEquipment+0x0
>-----CEquipmentItemInfo+0xC

That's the item ID used for whatever CEquipment entry that is, and users can look up item IDs (to see what item itis) via item database sites like sigkill or mabibase to see what item/hair the player is using.  Offsets +0x1C, +0x20, and +0x24 contain the item color IDs (4-byte hex) if you feel like including that as well, but it's not quite as useful.

**Comment by cursey** [comment]
Implemented in commit 412a2c3b82be2b68fa6e793c755672a7f5546a61
