### ISSUE TITLE
Server Cannot be Reached

### ISSUE THREAD

**Issue by siclx** [cursey/kanan-new#225]
Trying to use Kanan Launcher for multi-clients and it gives the "Server Cannot Be Reached" message after the update. Can login normally with nexon launcher. Anyone knows how to fix?

**Comment by PERKAndSETS** [comment]
From skimming over it I could be wrong, but you may need to update:
`if (cmdLine.empty()) {
                        cmdLine = (ostringstream{} <<
                            "\"" << m_clientPath << "\" " <<
                            "code:1622 " <<
                            "verstr:248 " <<
                            "ver:248 " <<
                            "locale:USA " <<
                            "env:Regular " <<
                            "setting:file://data/features.xml " <<
                            "logip:54.214.43.237 " <<
                            "logport:11002 " <<
                            "chatip:54.214.176.167 " <<
                            "chatport:8002 " <<
                            "/P:" << passport << " " <<
                            "-bgloader").str();
                    }`

**Comment by cursey** [comment]
Should be fixed in the latest release.

**Comment by siclx** [comment]
> Should be fixed in the latest release.

Yes, fixed! Thank you both.
