### ISSUE TITLE
Failed To create the process in Launcher/ Failed to open process in Loader

### ISSUE THREAD

**Issue by jchoochoo** [cursey/kanan-new#226]
I just downloaded the new 5/19 patch for kanan and extracted it in app data. It won't open in Loader and gives me the "Failed to open process" in cmd prompt. When I tried Launcher, it says "Failed to create the process" followed by "Failed to start Client.exe! Please check your settings and make sure you can login to the account from this computer normally".

This happened with the 5/16 version as well and I had no problems with the 5/5 version.

I downloaded the 5/5 version and tested to see if it worked afterward and that one does still load kanan,I just can't multiclient with that version, which I was hoping the 5/19 version would fix.

**Comment by cursey** [comment]
Check that your antivirus isn't deleting the new version of `Loader.exe`.

**Comment by jchoochoo** [comment]
Thank you it worked!
