### ISSUE TITLE
Latest release builds malfunctioning launcher

### ISSUE THREAD

**Issue by Warsen** [cursey/kanan-new#227]
I usually just replace my old release build with the new one. After updating to [2022.5.19](https://github.com/cursey/kanan-new/releases/tag/2022.5.19), when I run the launcher, it starts with some unknown garbage in the unlocking input text field. It's broken in a way that when I go to erase the input, the caret is 1 space after the last star *. Then when I use the correct unlock password, it fails and then the caret is put at the correct position again so a second attempt will work.

Surely this is some kind of issue where character bit size is different from what it used to be, and it's wrong. It was last working in [2022.5.5](https://github.com/cursey/kanan-new/releases/tag/2022.5.5)

**Comment by asdfasdfman** [comment]
I'm also having the same issue where I can't put my password in

**Comment by cursey** [comment]
Try the build available here: https://github.com/cursey/kanan-new/actions/runs/2355949748

Let me know if that fixes the issue you're both having. I was not able to reproduce this issue myself.

**Comment by asdfasdfman** [comment]
This build worked. Thank you so much!

**Comment by Warsen** [comment]
That fixes it. As a side note, I now find that I have to manually/explicitly run the both applications in administrator mode for them to work, rather than windows asking me for permission or whatever when I launch. This is not a problem at all, I just go into the program's properties and checkmark (Compatibility->Run this program as administrator)

**Comment by cursey** [comment]
> That fixes it. As a side note, I now find that I have to manually/explicitly run the both applications in administrator mode for them to work, rather than windows asking me for permission or whatever when I launch. This is not a problem at all, I just go into the program's properties and checkmark (Compatibility->Run this program as administrator)

This is a result of me switching build systems. I've just pushed a commit to fix this and will create a new release with the changes.
