### ISSUE TITLE
autoset mtu not working

### ISSUE THREAD

**Issue by tsruht** [cursey/kanan-new#228]
the log doesn't show it change my mtu 
![image](https://user-images.githubusercontent.com/20601311/169666942-35d9224e-3ee7-40fc-9ac8-9c0fa1e5f74e.png)

**Comment by cursey** [comment]
I've fixed this in commit 9608247ed00969d46d1f532cf627e07094c70a3c. You can download a dev build from https://github.com/cursey/kanan-new/actions/runs/2364494912 to test if this fixes it for you.

**Comment by tsruht** [comment]
you fixed it, thanks
