### ISSUE TITLE
Don't work with 64bit ver. client

### ISSUE THREAD

**Issue by uniunio** [cursey/kanan-new#257]
KR and JP have been updated to 64-bit client.
Failed to inject." is displayed.

**Comment by shaggyze** [comment]
> KR and JP have been updated to 64-bit client. Failed to inject." is displayed.

Yea, NA is aware, get used to it.

**Comment by cursey** [comment]
I don't play on KR or JP and don't intend on updating Kanan until NA gets the 64-bit update. I'll keep this issue open for now since it will need to be addressed.

**Comment by uniunio** [comment]
Thanks for the replies.
I can’t wait for that!
