### ISSUE TITLE
Kanan traceback issue

### ISSUE THREAD

**Issue by MiracleTrigger** [cursey/kanan-new#260]
Hello, I recently tried to install both python and Kanan mod and ran into this problem. I open Kanan batch file or even Kanan auto play batch file and it still gives me the same results. Could anyone help me figure what might be causing this issue?

![Capture kanan issue](https://user-images.githubusercontent.com/123513997/214429380-e61a4785-16e9-4e62-8b26-d5d10c835c34.JPG)

**Comment by Byteretention** [comment]
what exactly are you trying to run because this looks like old kanan

**Comment by MiracleTrigger** [comment]
Okay it does turn out that I had the old Kanan, thank you for pointing that out!
