### ISSUE TITLE
Request: "Fake" Devcat

### ISSUE THREAD

**Issue by AoiYui** [cursey/kanan-new#27]
I appologize in advance about the lack of formality or prior knowlege but lack any knowlege in code whatsoever. Okay! now that that's out of the way I'll get on with my request, I would like the return of the fake devcat title mod. I found it a huge help to have the hp of mobs available because it lets me plan my moves in advance to a certain extent. It's the main reason i choose to use your mod package. It would also be nice to bring some of the broken mods back. Thanks!

**Comment by Rydian** [comment]
It's there and works for me, try the latest build here.

https://ci.appveyor.com/project/cursey/kanan-new/build/artifacts

**Comment by cursey** [comment]
Yes, this mod is included.
