### ISSUE TITLE
Elf lag fix Scan returns too many results

### ISSUE THREAD

**Issue by Byteretention** [cursey/kanan-new#283]
Currently 48 89 5C 24 08 57 48 83 EC 20 48 8B 01 0F returns about 30 results in cheat engine so we cant be sure its patching the correct bytes. 

finding the correct area to patch and repairing it now

**Comment by Byteretention** [comment]
See https://github.com/cursey/kanan-new/pull/284

**Comment by cursey** [comment]
Merged
