### ISSUE TITLE
Request: display character upper muscles, lower muscles, and weight values.

### ISSUE THREAD

**Issue by bbogdn2** [cursey/kanan-new#298]

**Comment by comellow** [comment]
and can control the height or the weight, muscles, etc?

**Comment by kohupallintrax** [comment]
I updated the entity viewer to include this information. It only updates on server tick, but it would expose the exact values for you. You can grab the build artifact to try it out now or wait until the pull request is approved.

**Comment by bbogdn2** [comment]
Awesome, the build works like a charm.

**Comment by comellow** [comment]
@kohupallintrax Is it possible to adjust the in my mabinogi, not just viewing?

**Comment by kohupallintrax** [comment]
I just took a look and not easily. Changing the value from where its currently read doesn't change anything visually. A different function handles the character rendering portion of it on login or server tick so a specialized mod would need to be made for it. Displaying the value was a simple fix - changing and updating the char model would require a lot more time. I don't think I'll be looking into a feature like that anytime soon with how long I estimate it would take to find and implement.
