### ISSUE TITLE
Black box on startup

### ISSUE THREAD

**Issue by MaximusUrsus** [cursey/kanan-new#3]
Sorry if this is happening because of a step I missed, but the UI is just a black box. I see the UI as it should be for about 2 seconds when Mabi starts, but then it changes to all black. Re-opening the UI with Insert does not fix it.

https://i.gyazo.com/db0b8570ce065d7a59f23e92627d0443.jpg

**Comment by cursey** [comment]
Yeah someone messaged me privately about this happening to them as well. I can't force it to happen on my machine so it's hard for me to figure out a fix. I'll look over the ImGui renderer code soon and see if anything sticks out.

**Comment by MaximusUrsus** [comment]
That would definitely make it hard to solve. NVIDIA GeForce GTX 970.

**Comment by kleric** [comment]
I have the same issue on a GTX 1080. I can only get ImGui to show up when the map transitions (guessing cause nothing is being rendered).

You can still interact with it and drag it around, but it always renders as a black box.

**Comment by cursey** [comment]
When the map transitions? As in during a loading screen?

**Comment by kleric** [comment]
I didn't actually get a chance to do much testing. But I was able to get it to show up when entering Girgashy raid. When the screen fades to black, then fades into the mission.

**Comment by MaximusUrsus** [comment]
Any updates on this issue yet?

**Comment by Renharu** [comment]
I figured out the issue on my end.
Just disable Film style Post Shader

That fixed it for me.

**Comment by cursey** [comment]
@MaximusUrsus does @Renharu's fix work for you as well?

**Comment by cursey** [comment]
I think I've fixed the issue with commit 819a379. Can someone please confirm?

**Comment by kleric** [comment]
let me verify

**Comment by kleric** [comment]
yep it works now!

**Comment by MaximusUrsus** [comment]
Yup it works! Thanks.
