### ISSUE TITLE
EquipmentOverride seems to be broken

### ISSUE THREAD

**Issue by Tachiorz** [cursey/kanan-new#30]
[EquipmentOverride] convertInventoryIDToEquipmentSlot 00000000
@Rydian

**Comment by cursey** [comment]
Yea, I fixed this in commit 9a4d0acb1dc84e9a81a94f1f1a6a106309489345. Have you tried the latest build?

**Comment by xCryptic** [comment]
I can confirm it works with the latest build.

**Comment by cursey** [comment]
Ok, thanks.

**Comment by Tachiorz** [comment]
Sorry for false report, I wonder how I didn't noticed latest commit.
