### ISSUE TITLE
PetDesummonFix issue.

### ISSUE THREAD

**Issue by Shulzs** [cursey/kanan-new#305]
Found game crash when PetDesummonFix turn on.
Is this issue only on non-US mabi?

**Comment by kohupallintrax** [comment]
Assuming you've updated Kanan to its most recent release, Potentially, as it is currently working on the US client. I suspect the scan I use to find the addresses for the function I hook and one of the parameters of the function are grabbing an erroneous address in your region's client. 

Kanan is built for the NA client, its just that what we patch tends to be pretty similar with other regions that it can sometimes be used elsewhere.

**Comment by Shulzs** [comment]
Okay, thanks for reply.  
After the client changed to 64 bit, the differences of addresses is getting bigger and bigger, SAD T_T
