### ISSUE TITLE
Pets showing 0 minutes of summon time

### ISSUE THREAD

**Issue by anthonyjr2** [cursey/kanan-new#306]
Latest Kanan (2023.8.15). After 8/17 maintenance, all pets show 0 minute summoning time and their hotkeys are removed. Goes back to normal after a restart without injecting Kanan. Not sure if this was happening before maintenance as I was on 2023.8.12 beforehand.

**Comment by Shulzs** [comment]
Usually, it cause by xml file - Race.xml
If you have enable "Use data folder", maybe you should clear the outdated xml first.
