### ISSUE TITLE
Incorrect equipment IDs in character list

### ISSUE THREAD

**Issue by wizardtoast** [cursey/kanan-new#307]
I'm seeing IDs in character equipment that don't match the listed slots

For example in this picture, the torso ID is 29226, but that belongs to a hat: [Shadow Brigade Wig and Mask (F)](https://na.mabibase.com/item/29226)

The hands give an ID for [shoes](https://na.mabibase.com/item/2400034), the shoes give an ID for a [face](https://na.mabibase.com/item/5933/gfCharStyleCoupon), and so on.

![Client_5ITR3esCrs](https://github.com/cursey/kanan-new/assets/7133158/a7cc7ae5-22e7-42f7-9af4-57c881b6af81)

This is on the NA client with the [2023.8.15](https://github.com/cursey/kanan-new/releases/tag/2023.8.15) release of kanan.

**Comment by sportpp** [comment]
I've noticed this for awhile as well. On top of that however Equipment override itself seems to not be working as of the latest update.
