### ISSUE TITLE
Borderless window mode not working perfectly

### ISSUE THREAD

**Issue by nya-wn** [cursey/kanan-new#316]
honestly i can't begin to figure out how to describe this. it's been an issue since nexon added their own borderless window mode, but as a laptop player i like having my Taskbar visible at all times. 

[gif example](https://cdn.discordapp.com/attachments/587037309321478161/1147582392505204746/Client_R8p1ONRR1O.gif) 
basically, any time i reload the game in some way - i.e. channel changing - the window resizes to a smaller version for a moment and then goes back to full screen. 
unfortunately, when it does this it moves windows- like my bags if my inventory is open - in order to fit the window edges. 

I'm not sure why I'm having this issue qq I've used kanan with both steam and the nexon launcher with no change in outcome.

**Comment by kohupallintrax** [comment]
I utilize borderless window (borderless window option on display 1) fairly extensively for the same reason and have not had the issues you're describing. Do you use any additional overlay software? eg: Discord stream overlay, launch via steam, any other mods?

**Comment by kohupallintrax** [comment]
Sorry, never mind I was corrected by a friend - what you're describing DOES happen to me, I just play at a large resolution so it doesn't impact my bags like you experience. I don't have an immediate solution at the moment for you unfortunately.

**Comment by kohupallintrax** [comment]
Turns out if you change Screen Mode to "Borderless Fullscreen" In the Display settings in-game it resolves the issue for the most part.

**Comment by nya-wn** [comment]
i launch using steam primarily, but even with the nexon launcher it has the same effect. i believe i've done a kanan-only launch using the nexon launcher with the same issue, though i use kisara with my steam client.

i've always used kanan with other mods with no problem. for some reason it just started becoming glitchy after nexon added their own borderless option. 
![Client_D2GIQxnvVd](https://github.com/cursey/kanan-new/assets/50043449/9a67dca1-b4fa-409e-9ab3-8037204561c9)

idk if an ss of my settings will help, but here they are anyways

**Comment by codecumkey** [comment]
> i launch using steam primarily, but even with the nexon launcher it has the same effect. i believe i've done a kanan-only launch using the nexon launcher with the same issue, though i use kisara with my steam client.
> 
> i've always used kanan with other mods with no problem. for some reason it just started becoming glitchy after nexon added their own borderless option. ![Client_D2GIQxnvVd](https://user-images.githubusercontent.com/50043449/268427170-9a67dca1-b4fa-409e-9ab3-8037204561c9.png)
> 
> idk if an ss of my settings will help, but here they are anyways

if you read the comments above yours.
@kohupallintrax already gave the answer

> Turns out if you change Screen Mode to "Borderless Fullscreen" In the Display settings in-game it resolves the issue for the most part.

change screen mode to "borderless fullscreen"
this is a issue with mabinogis internal systems. it will try to reset window type when you cc or close the settings window.
kanan is just auto changing it back when it happens.
mabinogi will not try to reset window type if it has a matching type to what your doing in the settings.

too long cant read
change screen mode to "borderless fullscreen"

**Comment by nya-wn** [comment]
i'm bad at reading B) also for some reason thought that i had tried this i guess. thanks guys!! it worked 😭
