### ISSUE TITLE
Excess Deprecated Patches and Failure to Patch

### ISSUE THREAD

**Issue by Warsen** [cursey/kanan-new#323]
I've been using Kanan to multiclient for several years. When I am loading the game client, there is a good 30-50% chance that loading box that states "Loading Kanan..." stays on the screen and doesn't go away, the Celtic knot in the lower right corner stops spinning and the game has stopped responding. It has been this way for as long as I can remember. Recent changes by Satanachia had me curious to check what has been updated. To my surprise, only 1 file changed: Patches.json. I was sure this is more complicated than that, so I decided to examine the file. What I found is that this is actually an archive of every mod that has ever been made for Kanan since initial release. _That's not a good thing._ It takes more time to search and not find something 60+ times than it does to actually find something 30 times.

Some of these patches should never be used again, such as speeding up dialogue text. The game has it's own instant text setting. Some of these patches are repeats. The ability to disable the pop-up after the game is closed appears twice under two different names and descriptions. I decided to clean up the file. Once I did that, I never see the "Loading Kanan" window anymore. and in fact, I never have a client hang-up/freeze when booting up the game anymore.

I think you should remove all deprecated patches (features that are already in the game), duplicate patches, and patches which no one has any intent on finding the patterns again. I also think it would be a good idea to create a separate lite release which removes all these features that are intended for dev/debugging, such as listing out world and entity information and rendering options. It would make Kanan much more stable. Maybe just have a build-option for someone to re-enable the developer oriented patches. I can help with all this if you agree.

**Comment by codecumkey** [comment]
https://github.com/cursey/kanan-new/pull/324
