### ISSUE TITLE
Pet Desummon Fix not working

### ISSUE THREAD

**Issue by xenostar** [cursey/kanan-new#328]
The "Pet Desummon Fix" which allows you to press the pet summon hotkey to cancel the summon from that pet group no longer works after the patch. I'm guessing this is since there was a new hotkey added to the in-game hotkeys list for the Growth Window.

**Comment by kohupallintrax** [comment]
Fix has been submitted. Once approved it'll be fixed. Your suspicions are correct as to what had happened to break it.

**Comment by xenostar** [comment]
Thank you for working on that! @cursey Is it possible to cut a new release for this now that it is merged? It looks like CI failed for some reason.

**Comment by shaggyze** [comment]
> Thank you for working on that! @cursey Is it possible to cut a new release for this now that it is merged? It looks like CI failed for some reason.

she knows, vcpkg failed to install due to that server being down so she may change its version to use another mirror.

**Comment by kohupallintrax** [comment]
@xenostar The branch I used when working on the fix was able to have an artifact made that you can use in the meantime - it can be found here https://github.com/kohupallintrax/kanan-new/actions/runs/6911551075

The server went down shortly after requested the pull.

**Comment by cursey** [comment]
New release should be up shortly.

**Comment by xenostar** [comment]
Thank you guys. You're all amazing.
