### ISSUE TITLE
Wondering...

### ISSUE THREAD

**Issue by SariosAxe** [cursey/kanan-new#40]
New to modding in general, and was wondering if there's any way to save/not have to use the loader constantly and turn on the mods you want, like have a base line settings, Im currently only interested in quality of life mods, like bitmap font, naggle, CP view, and some other small stuff, and wanted to keep only those on, but whenever I turn mabinogi off I gotta redo all the configurations...
Am I missing something?

**Comment by draconis-pendragon** [comment]
You can edit the config.txt file to disable and enable patches.  This is generated upon first use of New Kanan.

**Comment by cursey** [comment]
NOTE: The config is automatically saved when you use the INSERT key to close the UI, not when pressing the circle button in the top right of the window.
