### ISSUE TITLE
HP keeps increasing in character info window

### ISSUE THREAD

**Issue by ZeroTheScyther** [cursey/kanan-new#43]
For some reason the HP keeps increasing over the limit.

![Image of HP](https://i.imgur.com/eIHk5so.jpg)

**Comment by y3tii** [comment]
HP does increase, this is normal and a part of the game itself. I believe this extra hp also acts as a buffer for the first hit you receive.

**Comment by cursey** [comment]
Yeah this information is read directly from the entity structure so its either a bug on mabi's part or by design. Either way I don't think there's anything to fix about this.
