### ISSUE TITLE
print screen key

### ISSUE THREAD

**Issue by tsruht** [cursey/kanan-new#54]
print screen causes the game to crash even with everything in kanan disabled

**Comment by cursey** [comment]
So I don't actually have a print screen button on my keyboard to actually test this. I'll ask around to try to confirm that this is an issue with Kanan for other users.

**Comment by Rydian** [comment]
Not experiencing it with a bunch of options turned on in the latest build (761856fa or 1.0.122), haven't experienced it previously.
