### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Tohkachi** [cursey/kanan-new#59]
Not sure what's going on, but Injecting succeeds. Near the end of loading Kanan, I get a Runtime Error from MS Viual C++ Runtime Library ever since Mabinogi updated on August 23rd, 2018.

**Comment by cursey** [comment]
Post your `log.txt` file.

**Comment by Tohkachi** [comment]
[log.txt](https://github.com/cursey/kanan-new/files/2319966/log.txt)
There you go, hope this helps!

**Comment by Tohkachi** [comment]
Just wanna follow up on this one, was it a fault on my end? I posted the log file but I'm not sure if that's the correct one or not.

**Comment by LoneDev6** [comment]
Can you post your runtime error message?
Also did you try starting Loader and then only after that starting Mabinogi?

**Comment by Tohkachi** [comment]
![image](https://user-images.githubusercontent.com/42679851/46644904-8e904d80-cb3f-11e8-929e-847d67d8cb2e.png)

This is what I get - and yes, I always run the loader as Administrator before running my Mabinogi from Steam. I doubt Steam has anything to do with it, given the error shown.

**Comment by LoneDev6** [comment]
Create a new folder and put ONLY kanan-new files into it.
I had the same problem when I added some other .json files in the kanan folder.

**Comment by Tohkachi** [comment]
Oh wow, it was an issue on my end!
Lots of apologies, and thanks for the help!
