### ISSUE TITLE
Request: Disable Pet Icon Rendering

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan-new#62]
When pets are hotkeyed, the hotkey shows the generic icon for that pet species instead, which is about as fast as any skill icon.  However the pet window shows renders of the pets instead, which is quite slow.  There used to be a mod to make the pet window use the generic icons as well, but I don't remember what it was in and didn't learn how it worked.

**Comment by Iuke121** [comment]
https://github.com/cursey/kanan-new/pull/63
I've added this on this pull request
