### ISSUE TITLE
Attach debugger to Mabi

### ISSUE THREAD

**Issue by LoneDev6** [cursey/kanan-new#66]
Hello,
does anyone knows how to attach a debugger to the game (for example CheatEngine to see which instruction is writing to specific address) without making mabi close itself after attaching it?

Thanks

**Comment by cursey** [comment]
Use Cheat Engines VEH debugger.
![cheatengine-x86_64_2018-09-17_06-30-10](https://user-images.githubusercontent.com/5798459/45626012-2fa94e00-ba43-11e8-88c7-46516169bcec.png)

**Comment by cursey** [comment]
Did my answer help? Or did you want instructions on a non-Cheat Engine debugger?

**Comment by LoneDev6** [comment]
Hello I was busy at work, I'll try that in a few hours when I'll be home.
I wanted instructions for CheatEngine so that's what I wanted to know ;)

**Comment by LoneDev6** [comment]
Working perfectly!

**Comment by LoneDev6** [comment]
Hello, I'm back at Mabinogi :D
Well, I tried using CheatEngine and after I attach it to Mabi game closes itself, did you got the same issue on latest updates?
