### ISSUE TITLE
Request: Save Equipment Override Entries

### ISSUE THREAD

**Issue by Emmarel** [cursey/kanan-new#67]
Fairly simple request. Make equipment override entries persist after logging off and logging back onto Mabi if possible.
Thanks! (;

**Comment by LoneDev6** [comment]
We must first find a way to trigger the player equipment rendering update, because now equipment override function of kanan to work needs the user to take the equipment in and out from the inventory after chosing the override id or the 3D model won't update

**Comment by cursey** [comment]
Actually it should just work if everything was saved to the config and loaded at startup. I just havn't gotten around to it.

**Comment by LoneDev6** [comment]
Would be cool to have stuff without buying it ingame xD I'll look into that

**Comment by LoneDev6** [comment]
Done testing, now I clean up the code and push it there

**Comment by cursey** [comment]
#68 has been merged.

**Comment by Emmarel** [comment]
Thanks a bunch! :)

**Comment by LoneDev6** [comment]
No problem! :D
