### ISSUE TITLE
Character List - Display Race

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan-new#72]
Right now the character list has an entry for the character's race, but it only displays a predefined string for the race, and only for a small number of known player races.  This makes it useless for checking out specific monsters, NPCs, and other entities.

For example I wanted to check the tags on this NPC.

https://i.imgur.com/v5qBR1t.png

But I don't know what race he is to look up that specific model to check the tags out.

**Comment by cursey** [comment]
Check commit a365c65d15dd375c0bd4431d08a9ce28bdc3b01e. Is this what you wanted? 
![client_2018-10-06_05-11-47](https://user-images.githubusercontent.com/5798459/46571247-62e64b00-c926-11e8-95e7-41bca525a324.png)

**Comment by Rydian** [comment]
Yup, that's the value!

**Comment by cursey** [comment]
Cool.
