### ISSUE TITLE
[Request] Uncap Auto-Production

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan-new#84]
```
66 39 86 FC010000     - cmp [esi+000001FC],ax
76 07                 - jna 0225FC1B
66 89 86 FC010000     - mov [esi+000001FC],ax
8B 8E B8010000        - mov ecx,[esi+000001B8]
```
First line checks if the stack of the materials being moved in is over 20 (**ax**) or not.
If not it keeps it the same.
If it is above 20 it sets the effective stack size down to 20.
Then line 4 takes the effective stack size (modified or not) as the queue amount.

Changing line 3 to copy over **cx** instead (or some custom value) will increase the auto-queue, at least for paper cranes and stuff, not sure how it'll work with multi-part items because I don't have enough mats to craft more than 20 guns at once or whatever.

Or you can edit the code in general to be a nicer mod that that, like edit line 4 to just move in 0x3E7 (999) or something.

**Comment by aef8234** [comment]
Yeah I agree, doesn't the read me say this mod has uncap prod?
