### ISSUE TITLE
how to open the configuration window

### ISSUE THREAD

**Issue by AoiYui** [cursey/kanan-new#90]
This is going to come off as a dumb question but bear with me. The delete button to open the config no longer works as of today or earlier so I can't figure out how open it can someone tell me what to do. 
Edit 1: Fixed typos
Edit 2: correction it was the insert key and that also doesn't work. I followed the instructions then hit launch client. 
Edit 3: I installed frontend beforehand would that interfere?
Edit 4: [Here's](https://imgur.com/XhiUvZZ) A picture of the Kanan launcher window
Edit 5: I ran it with admin since it asked in the first place
edit 6: The loader appears to be working so feel free to close this issue

**Comment by Rietty** [comment]
Is it possible you are using a laptop and the `Insert` key needs the `Fn` key pressed as well?

**Comment by AoiYui** [comment]
Can you walk me through the setup process just in case I missed something?

**Comment by AoiYui** [comment]
[Here's](https://imgur.com/XhiUvZZ) a picture of the kanan window.

**Comment by Rietty** [comment]
I'm pretty sure you have to log in/launch a client and you'll see config window when client is up.
