### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ithai9** [cursey/kanan-new#96]
Got an issue when opening up Mabi through Steam.

![image](https://user-images.githubusercontent.com/50198836/57067012-875e9780-6c69-11e9-995f-a74620452ff6.png)

Game closes immediately afterwards. What can I do?

**Comment by ithai9** [comment]
I also get this error with the Launcher.

![image](https://user-images.githubusercontent.com/50198836/57067162-e7553e00-6c69-11e9-94b3-2fb4a536f86c.png)

Really wanted to multi-client.

**Comment by ithai9** [comment]
I have downloaded the Microsoft Visual C++ Redistributable for Visual Studio 2019 both x86 and x64 to no avail.

**Comment by cursey** [comment]
Make sure there are no other `.json` files (besides `Patches.json`) in the folder with `Loader.exe` and `Kanan.dll`

**Comment by ithai9** [comment]
The only other .json file is steam_connector_config.json, which I can't seem to run the game without.

**Comment by cursey** [comment]
Kanan can be in its own folder wherever you want. Put it in a folder without extra `.json` files.

**Comment by ithai9** [comment]
It was that simple??? Thanks, it works!

**Comment by cursey** [comment]
The INSERT key opens and closes the menu.

**Comment by ithai9** [comment]
Thanks! Sorry, I should have saw the message at the top. Am I able to use Kanan to help me with life skills, such as cooking, blacksmith, and tailoring?
