### ISSUE TITLE
EquipmentOverride tail slot doesn't work

### ISSUE THREAD

**Issue by Maaxis** [cursey/kanan-new#98]
Simply put, the equipment item & color override for the tail slot doesn't seem to work, regardless of how I attempt to re-render the character (e.g. re-equipping the item, relogging, etc.) Also, Kanan's log doesn't state "Color/Item overwritten" like it usually would. All other slots work as intended.

Example of wings override working as intended, but tail override not functioning:

![Example](https://i.imgur.com/0nQMiNQ.png)

**Comment by cursey** [comment]
I will look into it (_soon_).
